# Generated by Django 4.2.11 on 2024-04-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotEntry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotentry',
            name='limit',
            field=models.IntegerField(default=6),
        ),
        # migrations.AddField(
        #     model_name='slotentry',
        #     name='name',
        #     field=models.CharField(max_length=100, null=True),
        # ),
    ]
