# Generated by Django 4.2.11 on 2024-04-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotEntry', '0002_slotentry_limit_slotentry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotentry',
            name='seat_available',
            field=models.IntegerField(default=0),
        ),
    ]
