# Generated by Django 4.2.11 on 2024-04-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slotEntry', '0004_slotentry_name'),
        ('slotbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='slotEntry.slotentry'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
