# Generated by Django 4.2.11 on 2024-04-24 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorUser', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
